name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test CI ran by ${{ github.actor }}
    runs-on: ubuntu-latest

    steps:
      - name: Prova stampa
        run: echo "caciotta"

  check-node:
    needs: test
    name: Verificare la versione installata di Node
    runs-on: ubuntu-latest
    
    steps:
      - name: ${{github.event}} sta innescando lo step di verifica Node
        run: node --version
    