name: CI Pipeline 

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test CI ran by ${{ github.actor }}
    runs-on: ubuntu-latest

    steps:
      - name: Prova stampa
        run: echo "caciotta"

    