name: CI Pipeline
env:
  NODE_VERSION: 24

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test CI ran by ${{ github.actor }}
    runs-on: ubuntu-latest

    steps:
      - name: Prova stampa
        run: echo "caciotta"

  setup-node:
    name: Setup node@24
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

  check-node:
    needs: setup-node
    name: Verificare la versione installata di Node
    runs-on: ubuntu-latest
    
    steps:
      - name: ${{github.event}} sta innescando lo step di verifica Node
        run: node --version
    