name: CI Pipeline
env:
  NODE_VERSION: 24

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test CI ran by ${{ github.actor }}
    runs-on: ubuntu-latest

    steps:
      - name: Prova stampa
        run: echo "caciotta"

  setup-node:
    needs: test
    name: Setup node@24
    runs-on: ubuntu-latest

    steps:
      - name: Check ENV
        run: echo ${{env.NODE_VERSION}}
      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: ${{github.event.head_commit.message}} sta innescando lo step di verifica Node
        run: node --version
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build App
        run: npm run build


    